# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_DB: db_trakdev
      POSTGRES_USER: Ab4ch3
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:./db/init.sql:/docker-entrypoint-initdb.d/init/sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
