version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    hostname: myhost
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - './db:/var/lib/postgresql/data'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: Ab4ch3
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trak_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# /var/www/html/LocalDev/A1-app-trakdev/db
# db
